# Generated by Django 5.1.7 on 2025-03-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('Not-Started', 'Not-Started'), ('In-Progress', 'In-Progress'), ('Completed', 'Completed')], default='Not-Started', max_length=20),
        ),
    ]
