# Generated by Django 5.1.7 on 2025-03-16 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='players',
        ),
        migrations.AddField(
            model_name='round',
            name='cups',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='round',
            name='round_number',
            field=models.IntegerField(default=1),
        ),
    ]
