# Generated by Django 5.1.7 on 2025-03-16 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_remove_round_players_round_cups_round_round_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='teamA_cups_made',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='teamA_cups_remaining',
            field=models.IntegerField(default=78),
        ),
        migrations.AddField(
            model_name='game',
            name='teamA_rack_status',
            field=models.CharField(choices=[('Initial', 'Initial'), ('Rerack', 'Rerack'), ('Zipper-7', 'Zipper-7'), ('Zipper-9', 'Zipper-9'), ('Gentlemans', 'Gentlemans')], default='Initial', max_length=20),
        ),
        migrations.AddField(
            model_name='game',
            name='teamB_cups_made',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='teamB_cups_remaining',
            field=models.IntegerField(default=78),
        ),
        migrations.AddField(
            model_name='game',
            name='teamB_rack_status',
            field=models.CharField(choices=[('Initial', 'Initial'), ('Rerack', 'Rerack'), ('Zipper-7', 'Zipper-7'), ('Zipper-9', 'Zipper-9'), ('Gentlemans', 'Gentlemans')], default='Initial', max_length=20),
        ),
        migrations.AddField(
            model_name='round',
            name='teamA_rack_status',
            field=models.CharField(choices=[('Initial', 'Initial'), ('Rerack', 'Rerack'), ('Zipper-7', 'Zipper-7'), ('Zipper-9', 'Zipper-9'), ('Gentlemans', 'Gentlemans')], default='Initial', max_length=20),
        ),
        migrations.AddField(
            model_name='round',
            name='teamB_rack_status',
            field=models.CharField(choices=[('Initial', 'Initial'), ('Rerack', 'Rerack'), ('Zipper-7', 'Zipper-7'), ('Zipper-9', 'Zipper-9'), ('Gentlemans', 'Gentlemans')], default='Initial', max_length=20),
        ),
        migrations.AlterField(
            model_name='round',
            name='round_number',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shots_taken', models.IntegerField(default=0)),
                ('cups_made', models.IntegerField(default=0)),
                ('accuracy', models.IntegerField(default=0)),
                ('death_cups', models.IntegerField(default=0)),
                ('clutch_cups', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_stats', to='games.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('player', 'game')},
            },
        ),
    ]
