# Generated by Django 5.1.7 on 2025-03-16 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_game_teama_cups_made_game_teama_cups_remaining_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_state',
            field=models.JSONField(default=dict),
        ),
    ]
