# Generated by Django 5.1.7 on 2025-03-16 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_game_game_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='game_state',
            new_name='cups',
        ),
    ]
