# Generated by Django 5.1.7 on 2025-03-17 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_playerstats_own_cups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstats',
            name='accuracy',
            field=models.FloatField(default=0.0),
        ),
    ]
